version: "3"
services:
 nginx:
  container_name: nginx
  image: nginx:1.13
  restart: always
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
 angular:
  container_name: front
  build: ./front
  restart: always
  ports:
   - "4200:4200"
 mysql:
   container_name: mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: dev
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: new_password
    MYSQL_ROOT_HOST: '%'
   ports:
    - "3306:3306"
   restart: always
 springboot:
   image: springboot-docker
   container_name: springboot-docker
   restart: always
   build:
    context: ./back
    dockerfile: Dockerfile
   working_dir: /back
   volumes:
    - ./back:/back
    - ~/.m2:/root/.m2
   expose:
    - "8080"
   ports:
    - "8080:8080"
   depends_on:
   - nginx
   - mysql
   command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
